//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace YMCL.Main.Public.Lang {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class MainLang {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal MainLang() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("YMCL.Main.Public.Lang.MainLang", typeof(MainLang).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   重写当前线程的 CurrentUICulture 属性，对
        ///   使用此强类型资源类的所有资源查找执行重写。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 添加新账户 的本地化字符串。
        /// </summary>
        public static string Account_AddAccount {
            get {
                return ResourceManager.GetString("Account_AddAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 取消 的本地化字符串。
        /// </summary>
        public static string Account_Cancel {
            get {
                return ResourceManager.GetString("Account_Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 复制代码并打开浏览器 的本地化字符串。
        /// </summary>
        public static string Account_CopyCodeAndOpenBrowser {
            get {
                return ResourceManager.GetString("Account_CopyCodeAndOpenBrowser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 删除选中账户 的本地化字符串。
        /// </summary>
        public static string Account_DelAccount {
            get {
                return ResourceManager.GetString("Account_DelAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 邮箱地址 的本地化字符串。
        /// </summary>
        public static string Account_Email {
            get {
                return ResourceManager.GetString("Account_Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 加载中... 的本地化字符串。
        /// </summary>
        public static string Account_Loading {
            get {
                return ResourceManager.GetString("Account_Loading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 微软登录 的本地化字符串。
        /// </summary>
        public static string Account_Microsoft {
            get {
                return ResourceManager.GetString("Account_Microsoft", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 离线登录 的本地化字符串。
        /// </summary>
        public static string Account_Offline {
            get {
                return ResourceManager.GetString("Account_Offline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 用户名不可为空 的本地化字符串。
        /// </summary>
        public static string Account_OfflineAccountAddBtn_Click_OfflineUserNameNull {
            get {
                return ResourceManager.GetString("Account_OfflineAccountAddBtn_Click_OfflineUserNameNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 账户密码 的本地化字符串。
        /// </summary>
        public static string Account_Password {
            get {
                return ResourceManager.GetString("Account_Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 认证服务器地址 的本地化字符串。
        /// </summary>
        public static string Account_ServerUrl {
            get {
                return ResourceManager.GetString("Account_ServerUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 确定 的本地化字符串。
        /// </summary>
        public static string Account_Sure {
            get {
                return ResourceManager.GetString("Account_Sure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 第三方登录 的本地化字符串。
        /// </summary>
        public static string Account_Third_Party {
            get {
                return ResourceManager.GetString("Account_Third_Party", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 游戏用户名 的本地化字符串。
        /// </summary>
        public static string Account_UserName {
            get {
                return ResourceManager.GetString("Account_UserName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 验证代码 的本地化字符串。
        /// </summary>
        public static string Account_VerificationCode {
            get {
                return ResourceManager.GetString("Account_VerificationCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 无附加安装 的本地化字符串。
        /// </summary>
        public static string AdditionalInstall {
            get {
                return ResourceManager.GetString("AdditionalInstall", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 添加文件 的本地化字符串。
        /// </summary>
        public static string AddLocalFile {
            get {
                return ResourceManager.GetString("AddLocalFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 全部 的本地化字符串。
        /// </summary>
        public static string All {
            get {
                return ResourceManager.GetString("All", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 所有版本 的本地化字符串。
        /// </summary>
        public static string AllVersion {
            get {
                return ResourceManager.GetString("AllVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 任意加载器 的本地化字符串。
        /// </summary>
        public static string AnyModLoader {
            get {
                return ResourceManager.GetString("AnyModLoader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 YMCL发生未处理的异常 的本地化字符串。
        /// </summary>
        public static string App_UnhandledException {
            get {
                return ResourceManager.GetString("App_UnhandledException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 应用数据 的本地化字符串。
        /// </summary>
        public static string AppData {
            get {
                return ResourceManager.GetString("AppData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 参数错误 的本地化字符串。
        /// </summary>
        public static string ArgsError {
            get {
                return ResourceManager.GetString("ArgsError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 自动安装 的本地化字符串。
        /// </summary>
        public static string AutoInstall {
            get {
                return ResourceManager.GetString("AutoInstall", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 自动进入服务器 的本地化字符串。
        /// </summary>
        public static string AutoJoinServer {
            get {
                return ResourceManager.GetString("AutoJoinServer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 开始下载 的本地化字符串。
        /// </summary>
        public static string BeginDownload {
            get {
                return ResourceManager.GetString("BeginDownload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 开始安装 的本地化字符串。
        /// </summary>
        public static string BeginInstall {
            get {
                return ResourceManager.GetString("BeginInstall", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 开始下载更新 的本地化字符串。
        /// </summary>
        public static string BeginUpdate {
            get {
                return ResourceManager.GetString("BeginUpdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 构建启动参数错误，检查启动设置是否有误 的本地化字符串。
        /// </summary>
        public static string BuildLaunchConfigError {
            get {
                return ResourceManager.GetString("BuildLaunchConfigError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 无法连接到api 的本地化字符串。
        /// </summary>
        public static string CannotConnectToApi {
            get {
                return ResourceManager.GetString("CannotConnectToApi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 YMCL无法找到当前需要的Java 的本地化字符串。
        /// </summary>
        public static string CannotFandRightJavaText {
            get {
                return ResourceManager.GetString("CannotFandRightJavaText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 居中对齐 的本地化字符串。
        /// </summary>
        public static string CenterAlignment {
            get {
                return ResourceManager.GetString("CenterAlignment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 检测音乐可用性... 的本地化字符串。
        /// </summary>
        public static string CheckSongAvailability {
            get {
                return ResourceManager.GetString("CheckSongAvailability", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 检查更新 的本地化字符串。
        /// </summary>
        public static string CheckUpdate {
            get {
                return ResourceManager.GetString("CheckUpdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 检查更新失败 的本地化字符串。
        /// </summary>
        public static string CheckUpdateFailed {
            get {
                return ResourceManager.GetString("CheckUpdateFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 点击查看任务进度 &gt;&gt; 的本地化字符串。
        /// </summary>
        public static string ClickToViewTaskCenter {
            get {
                return ResourceManager.GetString("ClickToViewTaskCenter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 编译C#错误 的本地化字符串。
        /// </summary>
        public static string ComPileCSharpError {
            get {
                return ResourceManager.GetString("ComPileCSharpError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 复制文件失败 的本地化字符串。
        /// </summary>
        public static string CopyFileFail {
            get {
                return ResourceManager.GetString("CopyFileFail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 创建任务 的本地化字符串。
        /// </summary>
        public static string CreateTask {
            get {
                return ResourceManager.GetString("CreateTask", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 自定义页面 (C#) 源代码错误 的本地化字符串。
        /// </summary>
        public static string CustomHomePageCSharpSouceError {
            get {
                return ResourceManager.GetString("CustomHomePageCSharpSouceError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 当前版本名称将被保存为 的本地化字符串。
        /// </summary>
        public static string CustomIdHandleText {
            get {
                return ResourceManager.GetString("CustomIdHandleText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 深色 的本地化字符串。
        /// </summary>
        public static string Dark {
            get {
                return ResourceManager.GetString("Dark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 桌面歌词 的本地化字符串。
        /// </summary>
        public static string DesktopLyric {
            get {
                return ResourceManager.GetString("DesktopLyric", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 桌面歌词文本对齐方向 的本地化字符串。
        /// </summary>
        public static string DesktopLyricTextAlignment {
            get {
                return ResourceManager.GetString("DesktopLyricTextAlignment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 桌面歌词文本大小 的本地化字符串。
        /// </summary>
        public static string DesktopLyricTextSize {
            get {
                return ResourceManager.GetString("DesktopLyricTextSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 色彩模式 的本地化字符串。
        /// </summary>
        public static string DisplayTheme {
            get {
                return ResourceManager.GetString("DisplayTheme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 下载失败 的本地化字符串。
        /// </summary>
        public static string DownloadFail {
            get {
                return ResourceManager.GetString("DownloadFail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 下载源 的本地化字符串。
        /// </summary>
        public static string DownloadSource {
            get {
                return ResourceManager.GetString("DownloadSource", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 下载线程过大可能导致设备卡顿 的本地化字符串。
        /// </summary>
        public static string DownloadThreadTooBig {
            get {
                return ResourceManager.GetString("DownloadThreadTooBig", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 下载更新 的本地化字符串。
        /// </summary>
        public static string DownloadUpdate {
            get {
                return ResourceManager.GetString("DownloadUpdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 发现新版本，是否下载更新？ 的本地化字符串。
        /// </summary>
        public static string DownloadUpdateQuestion {
            get {
                return ResourceManager.GetString("DownloadUpdateQuestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 编辑C# 的本地化字符串。
        /// </summary>
        public static string EditCSharp {
            get {
                return ResourceManager.GetString("EditCSharp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 编辑Xaml 的本地化字符串。
        /// </summary>
        public static string EditXaml {
            get {
                return ResourceManager.GetString("EditXaml", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 无法写入注册表 的本地化字符串。
        /// </summary>
        public static string FailToWriteReg {
            get {
                return ResourceManager.GetString("FailToWriteReg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 文件夹已存在 的本地化字符串。
        /// </summary>
        public static string FileExists {
            get {
                return ResourceManager.GetString("FileExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 发现新版本 的本地化字符串。
        /// </summary>
        public static string FindNewVersion {
            get {
                return ResourceManager.GetString("FindNewVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 更新下载完成 的本地化字符串。
        /// </summary>
        public static string FinishUpdate {
            get {
                return ResourceManager.GetString("FinishUpdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 文件夹 的本地化字符串。
        /// </summary>
        public static string Folder {
            get {
                return ResourceManager.GetString("Folder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 跟随系统 的本地化字符串。
        /// </summary>
        public static string FollowSystem {
            get {
                return ResourceManager.GetString("FollowSystem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 3s 后关闭此窗口 的本地化字符串。
        /// </summary>
        public static string GameExitLogWindow {
            get {
                return ResourceManager.GetString("GameExitLogWindow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 获取可安装版本失败 的本地化字符串。
        /// </summary>
        public static string GetInstallableVersionFail {
            get {
                return ResourceManager.GetString("GetInstallableVersionFail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 获取公告失败 的本地化字符串。
        /// </summary>
        public static string GetNoticeFail {
            get {
                return ResourceManager.GetString("GetNoticeFail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 获取歌词... 的本地化字符串。
        /// </summary>
        public static string GettingLyric {
            get {
                return ResourceManager.GetString("GettingLyric", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 获取音乐... 的本地化字符串。
        /// </summary>
        public static string GettingMusic {
            get {
                return ResourceManager.GetString("GettingMusic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 版本列表获取失败 的本地化字符串。
        /// </summary>
        public static string GetVersionListFail {
            get {
                return ResourceManager.GetString("GetVersionListFail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 YMCL 以 GPL-3.0 协议开放源代码，可以修改且分发，但不得删除原作品的标记，修改后的作品必须也采用 GPL 协议进行开源 的本地化字符串。
        /// </summary>
        public static string GPL3Text {
            get {
                return ResourceManager.GetString("GPL3Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 导入完成 的本地化字符串。
        /// </summary>
        public static string ImportFinish {
            get {
                return ResourceManager.GetString("ImportFinish", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 包含特殊字符 的本地化字符串。
        /// </summary>
        public static string IncludeSpecialWord {
            get {
                return ResourceManager.GetString("IncludeSpecialWord", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 连接中 的本地化字符串。
        /// </summary>
        public static string InitializeWindow_Connecting {
            get {
                return ResourceManager.GetString("InitializeWindow_Connecting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 连接失败 的本地化字符串。
        /// </summary>
        public static string InitializeWindow_ConnectionFailed {
            get {
                return ResourceManager.GetString("InitializeWindow_ConnectionFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 连接超时 的本地化字符串。
        /// </summary>
        public static string InitializeWindow_ConnectionTimeout {
            get {
                return ResourceManager.GetString("InitializeWindow_ConnectionTimeout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 需要管理员权限以初始化YMCL，点击确定使用管理员权限重启程序 的本地化字符串。
        /// </summary>
        public static string InitializeWindow_Download_AdministratorPermissionRequired {
            get {
                return ResourceManager.GetString("InitializeWindow_Download_AdministratorPermissionRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 下载完成 的本地化字符串。
        /// </summary>
        public static string InitializeWindow_DownloadFinish {
            get {
                return ResourceManager.GetString("InitializeWindow_DownloadFinish", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 无法完成下载？点击查看帮助 的本地化字符串。
        /// </summary>
        public static string InitializeWindow_DownloadHelp {
            get {
                return ResourceManager.GetString("InitializeWindow_DownloadHelp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 等待中 的本地化字符串。
        /// </summary>
        public static string InitializeWindow_DownloadWaiting {
            get {
                return ResourceManager.GetString("InitializeWindow_DownloadWaiting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 获取管理员权限失败，YMCL初始化失败 的本地化字符串。
        /// </summary>
        public static string InitializeWindow_FailedToObtainAdministratorPrivileges {
            get {
                return ResourceManager.GetString("InitializeWindow_FailedToObtainAdministratorPrivileges", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 YMCL初始化完成 的本地化字符串。
        /// </summary>
        public static string InitializeWindow_InitializeFinish {
            get {
                return ResourceManager.GetString("InitializeWindow_InitializeFinish", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 下一步 的本地化字符串。
        /// </summary>
        public static string InitializeWindow_NextSetpBtn {
            get {
                return ResourceManager.GetString("InitializeWindow_NextSetpBtn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 YMCL初始化 的本地化字符串。
        /// </summary>
        public static string InitializeWindow_Title {
            get {
                return ResourceManager.GetString("InitializeWindow_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 YMCL - 下载资源 的本地化字符串。
        /// </summary>
        public static string InitializeWindow_Title_Download {
            get {
                return ResourceManager.GetString("InitializeWindow_Title_Download", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 安装 的本地化字符串。
        /// </summary>
        public static string Install {
            get {
                return ResourceManager.GetString("Install", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 安装失败 的本地化字符串。
        /// </summary>
        public static string InstallFail {
            get {
                return ResourceManager.GetString("InstallFail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 安装完成 的本地化字符串。
        /// </summary>
        public static string InstallFinish {
            get {
                return ResourceManager.GetString("InstallFinish", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 安装预览 的本地化字符串。
        /// </summary>
        public static string InstallPreview {
            get {
                return ResourceManager.GetString("InstallPreview", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 当前已是最新版本 的本地化字符串。
        /// </summary>
        public static string LatestVersion {
            get {
                return ResourceManager.GetString("LatestVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 最新版本 的本地化字符串。
        /// </summary>
        public static string LatsetVersion {
            get {
                return ResourceManager.GetString("LatsetVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 添加文件夹 的本地化字符串。
        /// </summary>
        public static string Launch_AddMinecraftFolder {
            get {
                return ResourceManager.GetString("Launch_AddMinecraftFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 已存在此文件夹 的本地化字符串。
        /// </summary>
        public static string Launch_AddMinecraftFolder_Click_ExistsMinecraftFolder {
            get {
                return ResourceManager.GetString("Launch_AddMinecraftFolder_Click_ExistsMinecraftFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 需选择 .minecraft 文件夹 的本地化字符串。
        /// </summary>
        public static string Launch_AddMinecraftFolder_Click_NeedMinecraftFolder {
            get {
                return ResourceManager.GetString("Launch_AddMinecraftFolder_Click_NeedMinecraftFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 版本隔离 的本地化字符串。
        /// </summary>
        public static string Launch_AloneCore {
            get {
                return ResourceManager.GetString("Launch_AloneCore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 自动扫描 的本地化字符串。
        /// </summary>
        public static string Launch_AutoFindJava {
            get {
                return ResourceManager.GetString("Launch_AutoFindJava", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 扫描完成：发现{|}个Java，其中已有{|}个存在列表中 的本地化字符串。
        /// </summary>
        public static string Launch_AutoFindJava_Click_ScanCompleted {
            get {
                return ResourceManager.GetString("Launch_AutoFindJava_Click_ScanCompleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 让YMCL选择合适的Java 的本地化字符串。
        /// </summary>
        public static string Launch_AutoSelectJava {
            get {
                return ResourceManager.GetString("Launch_AutoSelectJava", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 自定义 的本地化字符串。
        /// </summary>
        public static string Launch_CustomSize {
            get {
                return ResourceManager.GetString("Launch_CustomSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 默认大小 的本地化字符串。
        /// </summary>
        public static string Launch_DefaultSize {
            get {
                return ResourceManager.GetString("Launch_DefaultSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 删除选中项 的本地化字符串。
        /// </summary>
        public static string Launch_DeleteSelectedItem {
            get {
                return ResourceManager.GetString("Launch_DeleteSelectedItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 移除选中项 的本地化字符串。
        /// </summary>
        public static string Launch_DelMinecraftFolder {
            get {
                return ResourceManager.GetString("Launch_DelMinecraftFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 全不选 的本地化字符串。
        /// </summary>
        public static string Launch_DeselectAll {
            get {
                return ResourceManager.GetString("Launch_DeselectAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 禁用选中项 的本地化字符串。
        /// </summary>
        public static string Launch_DisableSelectedItem {
            get {
                return ResourceManager.GetString("Launch_DisableSelectedItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 启用选中项 的本地化字符串。
        /// </summary>
        public static string Launch_EnableSelectedItem {
            get {
                return ResourceManager.GetString("Launch_EnableSelectedItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 全屏 的本地化字符串。
        /// </summary>
        public static string Launch_FullScreen {
            get {
                return ResourceManager.GetString("Launch_FullScreen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 游戏窗口 的本地化字符串。
        /// </summary>
        public static string Launch_GameWindow {
            get {
                return ResourceManager.GetString("Launch_GameWindow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 导入整合包 的本地化字符串。
        /// </summary>
        public static string Launch_ImportPack {
            get {
                return ResourceManager.GetString("Launch_ImportPack", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 自定义页面 (Xaml) 源代码错误 的本地化字符串。
        /// </summary>
        public static string Launch_Launch_CustomPageSourceError {
            get {
                return ResourceManager.GetString("Launch_Launch_CustomPageSourceError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 启动游戏 的本地化字符串。
        /// </summary>
        public static string Launch_LaunchBtn {
            get {
                return ResourceManager.GetString("Launch_LaunchBtn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 账户错误 的本地化字符串。
        /// </summary>
        public static string Launch_LaunchBtn_Click_AccountError {
            get {
                return ResourceManager.GetString("Launch_LaunchBtn_Click_AccountError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 YMCL无法找到当前需要的Java：Java 的本地化字符串。
        /// </summary>
        public static string Launch_LaunchBtn_Click_CannotFandRightJava {
            get {
                return ResourceManager.GetString("Launch_LaunchBtn_Click_CannotFandRightJava", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 启动完成，等待游戏窗口出现 的本地化字符串。
        /// </summary>
        public static string Launch_LaunchBtn_Click_FinishLaunch {
            get {
                return ResourceManager.GetString("Launch_LaunchBtn_Click_FinishLaunch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 游戏已退出 的本地化字符串。
        /// </summary>
        public static string Launch_LaunchBtn_Click_GameExit {
            get {
                return ResourceManager.GetString("Launch_LaunchBtn_Click_GameExit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Java错误 的本地化字符串。
        /// </summary>
        public static string Launch_LaunchBtn_Click_JavaError {
            get {
                return ResourceManager.GetString("Launch_LaunchBtn_Click_JavaError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 已启动 的本地化字符串。
        /// </summary>
        public static string Launch_LaunchBtn_Click_Launched {
            get {
                return ResourceManager.GetString("Launch_LaunchBtn_Click_Launched", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 启动成功 的本地化字符串。
        /// </summary>
        public static string Launch_LaunchBtn_Click_LaunchSuccess {
            get {
                return ResourceManager.GetString("Launch_LaunchBtn_Click_LaunchSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 未选择游戏核心或未找到游戏 的本地化字符串。
        /// </summary>
        public static string Launch_LaunchBtn_Click_NoChooseGame {
            get {
                return ResourceManager.GetString("Launch_LaunchBtn_Click_NoChooseGame", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 启动游戏 的本地化字符串。
        /// </summary>
        public static string Launch_LaunchGame {
            get {
                return ResourceManager.GetString("Launch_LaunchGame", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 账户错误 的本地化字符串。
        /// </summary>
        public static string Launch_LaunchGame_Click_AccountError {
            get {
                return ResourceManager.GetString("Launch_LaunchGame_Click_AccountError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 YMCL无法找到当前需要的Java：Java 的本地化字符串。
        /// </summary>
        public static string Launch_LaunchGame_Click_CannotFandRightJava {
            get {
                return ResourceManager.GetString("Launch_LaunchGame_Click_CannotFandRightJava", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 启动完成，等待游戏窗口出现 的本地化字符串。
        /// </summary>
        public static string Launch_LaunchGame_Click_FinishLaunch {
            get {
                return ResourceManager.GetString("Launch_LaunchGame_Click_FinishLaunch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 游戏已退出 的本地化字符串。
        /// </summary>
        public static string Launch_LaunchGame_Click_GameExit {
            get {
                return ResourceManager.GetString("Launch_LaunchGame_Click_GameExit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Java错误 的本地化字符串。
        /// </summary>
        public static string Launch_LaunchGame_Click_JavaError {
            get {
                return ResourceManager.GetString("Launch_LaunchGame_Click_JavaError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 启动完成 的本地化字符串。
        /// </summary>
        public static string Launch_LaunchGame_Click_Launched {
            get {
                return ResourceManager.GetString("Launch_LaunchGame_Click_Launched", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 启动成功 的本地化字符串。
        /// </summary>
        public static string Launch_LaunchGame_Click_LaunchSuccess {
            get {
                return ResourceManager.GetString("Launch_LaunchGame_Click_LaunchSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 未选择游戏版本或未找到此版本 的本地化字符串。
        /// </summary>
        public static string Launch_LaunchGame_Click_NoChooseGame {
            get {
                return ResourceManager.GetString("Launch_LaunchGame_Click_NoChooseGame", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 获取版本列表发生错误 的本地化字符串。
        /// </summary>
        public static string Launch_LoadMinecraftVersion_GetVersionListError {
            get {
                return ResourceManager.GetString("Launch_LoadMinecraftVersion_GetVersionListError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 手动添加 的本地化字符串。
        /// </summary>
        public static string Launch_ManualAddJava {
            get {
                return ResourceManager.GetString("Launch_ManualAddJava", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 已存在此Java 的本地化字符串。
        /// </summary>
        public static string Launch_ManualAddJava_Click_ExistsJava {
            get {
                return ResourceManager.GetString("Launch_ManualAddJava_Click_ExistsJava", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 最大运行内存 的本地化字符串。
        /// </summary>
        public static string Launch_MaxMem {
            get {
                return ResourceManager.GetString("Launch_MaxMem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Minecraft文件夹 的本地化字符串。
        /// </summary>
        public static string Launch_MinecraftFolder {
            get {
                return ResourceManager.GetString("Launch_MinecraftFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Mod 文件夹 的本地化字符串。
        /// </summary>
        public static string Launch_ModFolder {
            get {
                return ResourceManager.GetString("Launch_ModFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 &lt;未选择游戏核心&gt; 的本地化字符串。
        /// </summary>
        public static string Launch_NoChooseGame {
            get {
                return ResourceManager.GetString("Launch_NoChooseGame", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 显示输出日志 的本地化字符串。
        /// </summary>
        public static string Launch_OutputLogReceived {
            get {
                return ResourceManager.GetString("Launch_OutputLogReceived", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 刷新 的本地化字符串。
        /// </summary>
        public static string Launch_Refresh {
            get {
                return ResourceManager.GetString("Launch_Refresh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 资源包文件夹 的本地化字符串。
        /// </summary>
        public static string Launch_ResourcePackFolder {
            get {
                return ResourceManager.GetString("Launch_ResourcePackFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 存档文件夹 的本地化字符串。
        /// </summary>
        public static string Launch_SavesFolder {
            get {
                return ResourceManager.GetString("Launch_SavesFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 全选 的本地化字符串。
        /// </summary>
        public static string Launch_SelectAll {
            get {
                return ResourceManager.GetString("Launch_SelectAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 已选择{|}个文件 的本地化字符串。
        /// </summary>
        public static string Launch_SelectedModCount {
            get {
                return ResourceManager.GetString("Launch_SelectedModCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 光影包文件夹 的本地化字符串。
        /// </summary>
        public static string Launch_ShaderPackFolder {
            get {
                return ResourceManager.GetString("Launch_ShaderPackFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Mods 的本地化字符串。
        /// </summary>
        public static string Launch_TabItem_Mods {
            get {
                return ResourceManager.GetString("Launch_TabItem_Mods", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 概览 的本地化字符串。
        /// </summary>
        public static string Launch_TabItem_Overview {
            get {
                return ResourceManager.GetString("Launch_TabItem_Overview", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 设置 的本地化字符串。
        /// </summary>
        public static string Launch_TabItem_Settings {
            get {
                return ResourceManager.GetString("Launch_TabItem_Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似  版本列表  的本地化字符串。
        /// </summary>
        public static string Launch_ToVersionList {
            get {
                return ResourceManager.GetString("Launch_ToVersionList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似  版本设置  的本地化字符串。
        /// </summary>
        public static string Launch_ToVersionSetting {
            get {
                return ResourceManager.GetString("Launch_ToVersionSetting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 使用全局设置 的本地化字符串。
        /// </summary>
        public static string Launch_UseGlobalSettings {
            get {
                return ResourceManager.GetString("Launch_UseGlobalSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 版本文件夹 的本地化字符串。
        /// </summary>
        public static string Launch_VersionFolder {
            get {
                return ResourceManager.GetString("Launch_VersionFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 版本列表 的本地化字符串。
        /// </summary>
        public static string Launch_VersionList {
            get {
                return ResourceManager.GetString("Launch_VersionList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 自定义主界面 的本地化字符串。
        /// </summary>
        public static string Launcher_SettingItem_CustomMainPage {
            get {
                return ResourceManager.GetString("Launcher_SettingItem_CustomMainPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 编辑 的本地化字符串。
        /// </summary>
        public static string Launcher_SettingItem_EditCustomHomePage {
            get {
                return ResourceManager.GetString("Launcher_SettingItem_EditCustomHomePage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 语言 的本地化字符串。
        /// </summary>
        public static string Launcher_SettingItem_Language {
            get {
                return ResourceManager.GetString("Launcher_SettingItem_Language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 将启用自定义页面，YMCL不保证自定义内容安全性，不安全的自定义内容可能会导致设备遭受攻击等 的本地化字符串。
        /// </summary>
        public static string Launcher_UseCustomHomePageToggle_Toggled_On_Info {
            get {
                return ResourceManager.GetString("Launcher_UseCustomHomePageToggle_Toggled_On_Info", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 启动失败 的本地化字符串。
        /// </summary>
        public static string LaunchFail {
            get {
                return ResourceManager.GetString("LaunchFail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 左对齐 的本地化字符串。
        /// </summary>
        public static string LeftAlignment {
            get {
                return ResourceManager.GetString("LeftAlignment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 浅色 的本地化字符串。
        /// </summary>
        public static string Light {
            get {
                return ResourceManager.GetString("Light", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 → 加载更多 ← 的本地化字符串。
        /// </summary>
        public static string LoadingMore {
            get {
                return ResourceManager.GetString("LoadingMore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 加载版本设置失败 的本地化字符串。
        /// </summary>
        public static string LoadVersionSettingFail {
            get {
                return ResourceManager.GetString("LoadVersionSettingFail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 本地文件 的本地化字符串。
        /// </summary>
        public static string LocalFile {
            get {
                return ResourceManager.GetString("LocalFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 登录失败 的本地化字符串。
        /// </summary>
        public static string LoginFail {
            get {
                return ResourceManager.GetString("LoginFail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似    下载 的本地化字符串。
        /// </summary>
        public static string MainWindow_NavigationDownload {
            get {
                return ResourceManager.GetString("MainWindow_NavigationDownload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似    启动 的本地化字符串。
        /// </summary>
        public static string MainWindow_NavigationLaunch {
            get {
                return ResourceManager.GetString("MainWindow_NavigationLaunch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似    更多 的本地化字符串。
        /// </summary>
        public static string MainWindow_NavigationMore {
            get {
                return ResourceManager.GetString("MainWindow_NavigationMore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似    音乐 的本地化字符串。
        /// </summary>
        public static string MainWindow_NavigationMusic {
            get {
                return ResourceManager.GetString("MainWindow_NavigationMusic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似    设置 的本地化字符串。
        /// </summary>
        public static string MainWindow_NavigationSetting {
            get {
                return ResourceManager.GetString("MainWindow_NavigationSetting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 YMCL 的本地化字符串。
        /// </summary>
        public static string MainWindow_Title {
            get {
                return ResourceManager.GetString("MainWindow_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 最大下载线程 的本地化字符串。
        /// </summary>
        public static string MaximumDownloadThread {
            get {
                return ResourceManager.GetString("MaximumDownloadThread", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Minecraft版本 的本地化字符串。
        /// </summary>
        public static string MinecraftVersion {
            get {
                return ResourceManager.GetString("MinecraftVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Mod名称 的本地化字符串。
        /// </summary>
        public static string ModName {
            get {
                return ResourceManager.GetString("ModName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 音乐 的本地化字符串。
        /// </summary>
        public static string Music {
            get {
                return ResourceManager.GetString("Music", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 音乐播放器 的本地化字符串。
        /// </summary>
        public static string MusicPlayer {
            get {
                return ResourceManager.GetString("MusicPlayer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 音乐不可用 的本地化字符串。
        /// </summary>
        public static string MusicUnavailable {
            get {
                return ResourceManager.GetString("MusicUnavailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 需要重启YMCL 的本地化字符串。
        /// </summary>
        public static string NeedRestartApp {
            get {
                return ResourceManager.GetString("NeedRestartApp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 网络文件 的本地化字符串。
        /// </summary>
        public static string NetFile {
            get {
                return ResourceManager.GetString("NetFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 尚未选择音乐 的本地化字符串。
        /// </summary>
        public static string NoChooseSong {
            get {
                return ResourceManager.GetString("NoChooseSong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 无网络连接 的本地化字符串。
        /// </summary>
        public static string NoNetwork {
            get {
                return ResourceManager.GetString("NoNetwork", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 公告 的本地化字符串。
        /// </summary>
        public static string Notice {
            get {
                return ResourceManager.GetString("Notice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 关闭 的本地化字符串。
        /// </summary>
        public static string Off {
            get {
                return ResourceManager.GetString("Off", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 远古版 的本地化字符串。
        /// </summary>
        public static string OldVersion {
            get {
                return ResourceManager.GetString("OldVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 开启 的本地化字符串。
        /// </summary>
        public static string On {
            get {
                return ResourceManager.GetString("On", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 → 打开 ← 的本地化字符串。
        /// </summary>
        public static string OpenApp {
            get {
                return ResourceManager.GetString("OpenApp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 打开文件夹 的本地化字符串。
        /// </summary>
        public static string OpenFolder {
            get {
                return ResourceManager.GetString("OpenFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 开源项目使用表 的本地化字符串。
        /// </summary>
        public static string OpenSourceProjectUsageTable {
            get {
                return ResourceManager.GetString("OpenSourceProjectUsageTable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 打开任务中心 的本地化字符串。
        /// </summary>
        public static string OpenTaskCenter {
            get {
                return ResourceManager.GetString("OpenTaskCenter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 正式版 的本地化字符串。
        /// </summary>
        public static string ReleaseVersion {
            get {
                return ResourceManager.GetString("ReleaseVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 重复启动YMCL，转到系统托盘查看已打开的YMCL实例 的本地化字符串。
        /// </summary>
        public static string RepeatOpen {
            get {
                return ResourceManager.GetString("RepeatOpen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 返回 的本地化字符串。
        /// </summary>
        public static string Return {
            get {
                return ResourceManager.GetString("Return", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 右对齐 的本地化字符串。
        /// </summary>
        public static string RightAlignment {
            get {
                return ResourceManager.GetString("RightAlignment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 已取消保存 的本地化字符串。
        /// </summary>
        public static string SaveCancel {
            get {
                return ResourceManager.GetString("SaveCancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 保存音频文件 的本地化字符串。
        /// </summary>
        public static string SaveMusicFile {
            get {
                return ResourceManager.GetString("SaveMusicFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 保存皮肤文件 的本地化字符串。
        /// </summary>
        public static string SaveSkin {
            get {
                return ResourceManager.GetString("SaveSkin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 保存成功 的本地化字符串。
        /// </summary>
        public static string SaveSuccess {
            get {
                return ResourceManager.GetString("SaveSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 搜索失败 的本地化字符串。
        /// </summary>
        public static string SearchFail {
            get {
                return ResourceManager.GetString("SearchFail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 搜索无结果 的本地化字符串。
        /// </summary>
        public static string SearchNoResult {
            get {
                return ResourceManager.GetString("SearchNoResult", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 选择文件夹 的本地化字符串。
        /// </summary>
        public static string SeletFolder {
            get {
                return ResourceManager.GetString("SeletFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 启动器 的本地化字符串。
        /// </summary>
        public static string Setting_Navigation_About {
            get {
                return ResourceManager.GetString("Setting_Navigation_About", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 账户 的本地化字符串。
        /// </summary>
        public static string Setting_Navigation_Account {
            get {
                return ResourceManager.GetString("Setting_Navigation_Account", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 下载 的本地化字符串。
        /// </summary>
        public static string Setting_Navigation_Download {
            get {
                return ResourceManager.GetString("Setting_Navigation_Download", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 启动 的本地化字符串。
        /// </summary>
        public static string Setting_Navigation_Launch {
            get {
                return ResourceManager.GetString("Setting_Navigation_Launch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 个性化 的本地化字符串。
        /// </summary>
        public static string Setting_Navigation_Launcher {
            get {
                return ResourceManager.GetString("Setting_Navigation_Launcher", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 显示窗口 的本地化字符串。
        /// </summary>
        public static string ShowWindow {
            get {
                return ResourceManager.GetString("ShowWindow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 预览版 的本地化字符串。
        /// </summary>
        public static string SnapshotVersion {
            get {
                return ResourceManager.GetString("SnapshotVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 音频文件 的本地化字符串。
        /// </summary>
        public static string SongFile {
            get {
                return ResourceManager.GetString("SongFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 源文件不存在，它可能被移动、重命名或删除 的本地化字符串。
        /// </summary>
        public static string SourceFileNotExists {
            get {
                return ResourceManager.GetString("SourceFileNotExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 将以下Mod移动到回收站 的本地化字符串。
        /// </summary>
        public static string SureDeleteMod {
            get {
                return ResourceManager.GetString("SureDeleteMod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 任务进度 的本地化字符串。
        /// </summary>
        public static string TaskProgressWindow_Title {
            get {
                return ResourceManager.GetString("TaskProgressWindow_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 任务中心 的本地化字符串。
        /// </summary>
        public static string TasksCenter {
            get {
                return ResourceManager.GetString("TasksCenter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 主题色 的本地化字符串。
        /// </summary>
        public static string ThemeColor {
            get {
                return ResourceManager.GetString("ThemeColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 百宝箱 的本地化字符串。
        /// </summary>
        public static string TreasureBox {
            get {
                return ResourceManager.GetString("TreasureBox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 彻底退出 的本地化字符串。
        /// </summary>
        public static string TrueExit {
            get {
                return ResourceManager.GetString("TrueExit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 更新内容 的本地化字符串。
        /// </summary>
        public static string UpdateInfo {
            get {
                return ResourceManager.GetString("UpdateInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 应用更改 的本地化字符串。
        /// </summary>
        public static string UseChange {
            get {
                return ResourceManager.GetString("UseChange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 外部启动 的本地化字符串。
        /// </summary>
        public static string UseCommandLaunchYMCL {
            get {
                return ResourceManager.GetString("UseCommandLaunchYMCL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 通过命令启动YMCL 的本地化字符串。
        /// </summary>
        public static string UseCommandLaunchYMCLDescription {
            get {
                return ResourceManager.GetString("UseCommandLaunchYMCLDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 使用全局设置 的本地化字符串。
        /// </summary>
        public static string UseGlobalSetting {
            get {
                return ResourceManager.GetString("UseGlobalSetting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 用户数据 的本地化字符串。
        /// </summary>
        public static string UserData {
            get {
                return ResourceManager.GetString("UserData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 用户数据处理失败 的本地化字符串。
        /// </summary>
        public static string UserDataError {
            get {
                return ResourceManager.GetString("UserDataError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 正在验证账户 的本地化字符串。
        /// </summary>
        public static string VerifyingAccount {
            get {
                return ResourceManager.GetString("VerifyingAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 查看更新内容 的本地化字符串。
        /// </summary>
        public static string ViewUpdate {
            get {
                return ResourceManager.GetString("ViewUpdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 等待游戏窗口出现 的本地化字符串。
        /// </summary>
        public static string WaitForGameWindowAppear {
            get {
                return ResourceManager.GetString("WaitForGameWindowAppear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 写入完成 的本地化字符串。
        /// </summary>
        public static string WriteFinish {
            get {
                return ResourceManager.GetString("WriteFinish", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 写入注册表 的本地化字符串。
        /// </summary>
        public static string WriteReg {
            get {
                return ResourceManager.GetString("WriteReg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 写出快捷方式 的本地化字符串。
        /// </summary>
        public static string WriteShortCut {
            get {
                return ResourceManager.GetString("WriteShortCut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 创建用于启动YMCL的快捷方式 的本地化字符串。
        /// </summary>
        public static string WriteShortCutDescription {
            get {
                return ResourceManager.GetString("WriteShortCutDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 邮箱不可为空 的本地化字符串。
        /// </summary>
        public static string YggdrasilEmailIsEmpty {
            get {
                return ResourceManager.GetString("YggdrasilEmailIsEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 密码不可为空 的本地化字符串。
        /// </summary>
        public static string YggdrasilPasswordIsEmpty {
            get {
                return ResourceManager.GetString("YggdrasilPasswordIsEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 验证服务器不可为空 的本地化字符串。
        /// </summary>
        public static string YggdrasilServerUrlIsEmpty {
            get {
                return ResourceManager.GetString("YggdrasilServerUrlIsEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Ymcl 更新可用 的本地化字符串。
        /// </summary>
        public static string YMCLNewVersion {
            get {
                return ResourceManager.GetString("YMCLNewVersion", resourceCulture);
            }
        }
    }
}
