//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace YMCL.Main.Public.Lang {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class MainLang {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal MainLang() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("YMCL.Main.Public.Lang.MainLang", typeof(MainLang).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   重写当前线程的 CurrentUICulture 属性，对
        ///   使用此强类型资源类的所有资源查找执行重写。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 添加新账户 的本地化字符串。
        /// </summary>
        public static string Account_AddAccount {
            get {
                return ResourceManager.GetString("Account_AddAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 取消 的本地化字符串。
        /// </summary>
        public static string Account_Cancel {
            get {
                return ResourceManager.GetString("Account_Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 复制代码并打开浏览器 的本地化字符串。
        /// </summary>
        public static string Account_CopyCodeAndOpenBrowser {
            get {
                return ResourceManager.GetString("Account_CopyCodeAndOpenBrowser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 删除选中账户 的本地化字符串。
        /// </summary>
        public static string Account_DelAccount {
            get {
                return ResourceManager.GetString("Account_DelAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 邮箱地址 的本地化字符串。
        /// </summary>
        public static string Account_Email {
            get {
                return ResourceManager.GetString("Account_Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 加载中... 的本地化字符串。
        /// </summary>
        public static string Account_Loading {
            get {
                return ResourceManager.GetString("Account_Loading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 微软登录 的本地化字符串。
        /// </summary>
        public static string Account_Microsoft {
            get {
                return ResourceManager.GetString("Account_Microsoft", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 离线登录 的本地化字符串。
        /// </summary>
        public static string Account_Offline {
            get {
                return ResourceManager.GetString("Account_Offline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 用户名不可为空 的本地化字符串。
        /// </summary>
        public static string Account_OfflineAccountAddBtn_Click_OfflineUserNameNull {
            get {
                return ResourceManager.GetString("Account_OfflineAccountAddBtn_Click_OfflineUserNameNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 账户密码 的本地化字符串。
        /// </summary>
        public static string Account_Password {
            get {
                return ResourceManager.GetString("Account_Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 认证服务器地址 的本地化字符串。
        /// </summary>
        public static string Account_ServerUrl {
            get {
                return ResourceManager.GetString("Account_ServerUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 确定 的本地化字符串。
        /// </summary>
        public static string Account_Sure {
            get {
                return ResourceManager.GetString("Account_Sure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 第三方登录 的本地化字符串。
        /// </summary>
        public static string Account_Third_Party {
            get {
                return ResourceManager.GetString("Account_Third_Party", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 游戏用户名 的本地化字符串。
        /// </summary>
        public static string Account_UserName {
            get {
                return ResourceManager.GetString("Account_UserName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 验证代码 的本地化字符串。
        /// </summary>
        public static string Account_VerificationCode {
            get {
                return ResourceManager.GetString("Account_VerificationCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 YMCL发生未处理的异常，将崩溃退出 的本地化字符串。
        /// </summary>
        public static string App_UnhandledException {
            get {
                return ResourceManager.GetString("App_UnhandledException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 参数错误 的本地化字符串。
        /// </summary>
        public static string ArgsError {
            get {
                return ResourceManager.GetString("ArgsError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 开始下载更新 的本地化字符串。
        /// </summary>
        public static string BeginUpdate {
            get {
                return ResourceManager.GetString("BeginUpdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 构建启动参数错误，检查启动设置是否有误 的本地化字符串。
        /// </summary>
        public static string BuildLaunchConfigError {
            get {
                return ResourceManager.GetString("BuildLaunchConfigError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 检查更新 的本地化字符串。
        /// </summary>
        public static string CheckUpdate {
            get {
                return ResourceManager.GetString("CheckUpdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 检查更新失败 的本地化字符串。
        /// </summary>
        public static string CheckUpdateFailed {
            get {
                return ResourceManager.GetString("CheckUpdateFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 深色 的本地化字符串。
        /// </summary>
        public static string Dark {
            get {
                return ResourceManager.GetString("Dark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 色彩模式 的本地化字符串。
        /// </summary>
        public static string DisplayTheme {
            get {
                return ResourceManager.GetString("DisplayTheme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 下载失败 的本地化字符串。
        /// </summary>
        public static string DownloadFail {
            get {
                return ResourceManager.GetString("DownloadFail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 下载源 的本地化字符串。
        /// </summary>
        public static string DownloadSource {
            get {
                return ResourceManager.GetString("DownloadSource", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 下载更新 的本地化字符串。
        /// </summary>
        public static string DownloadUpdate {
            get {
                return ResourceManager.GetString("DownloadUpdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 发现新版本，是否下载更新？ 的本地化字符串。
        /// </summary>
        public static string DownloadUpdateQuestion {
            get {
                return ResourceManager.GetString("DownloadUpdateQuestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 发现新版本 的本地化字符串。
        /// </summary>
        public static string FindNewVersion {
            get {
                return ResourceManager.GetString("FindNewVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 更新下载完成 的本地化字符串。
        /// </summary>
        public static string FinishUpdate {
            get {
                return ResourceManager.GetString("FinishUpdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 跟随系统 的本地化字符串。
        /// </summary>
        public static string FollowSystem {
            get {
                return ResourceManager.GetString("FollowSystem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 3s 后关闭此窗口 的本地化字符串。
        /// </summary>
        public static string GameExitLogWindow {
            get {
                return ResourceManager.GetString("GameExitLogWindow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 YMCL 以 GPL-3.0 协议开放源代码，可以修改且分发，但不得删除原作品的标记，修改后的作品必须也采用 GPL 协议进行开源 的本地化字符串。
        /// </summary>
        public static string GPL3Text {
            get {
                return ResourceManager.GetString("GPL3Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 连接中 的本地化字符串。
        /// </summary>
        public static string InitializeWindow_Connecting {
            get {
                return ResourceManager.GetString("InitializeWindow_Connecting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 连接失败 的本地化字符串。
        /// </summary>
        public static string InitializeWindow_ConnectionFailed {
            get {
                return ResourceManager.GetString("InitializeWindow_ConnectionFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 连接超时 的本地化字符串。
        /// </summary>
        public static string InitializeWindow_ConnectionTimeout {
            get {
                return ResourceManager.GetString("InitializeWindow_ConnectionTimeout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 需要管理员权限以初始化YMCL，点击确定使用管理员权限重启程序 的本地化字符串。
        /// </summary>
        public static string InitializeWindow_Download_AdministratorPermissionRequired {
            get {
                return ResourceManager.GetString("InitializeWindow_Download_AdministratorPermissionRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 下载完成 的本地化字符串。
        /// </summary>
        public static string InitializeWindow_DownloadFinish {
            get {
                return ResourceManager.GetString("InitializeWindow_DownloadFinish", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 无法完成下载？点击查看帮助 的本地化字符串。
        /// </summary>
        public static string InitializeWindow_DownloadHelp {
            get {
                return ResourceManager.GetString("InitializeWindow_DownloadHelp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 等待中 的本地化字符串。
        /// </summary>
        public static string InitializeWindow_DownloadWaiting {
            get {
                return ResourceManager.GetString("InitializeWindow_DownloadWaiting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 获取管理员权限失败，YMCL初始化失败 的本地化字符串。
        /// </summary>
        public static string InitializeWindow_FailedToObtainAdministratorPrivileges {
            get {
                return ResourceManager.GetString("InitializeWindow_FailedToObtainAdministratorPrivileges", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 YMCL初始化完成 的本地化字符串。
        /// </summary>
        public static string InitializeWindow_InitializeFinish {
            get {
                return ResourceManager.GetString("InitializeWindow_InitializeFinish", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 下一步 的本地化字符串。
        /// </summary>
        public static string InitializeWindow_NextSetpBtn {
            get {
                return ResourceManager.GetString("InitializeWindow_NextSetpBtn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 YMCL初始化 的本地化字符串。
        /// </summary>
        public static string InitializeWindow_Title {
            get {
                return ResourceManager.GetString("InitializeWindow_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 YMCL - 下载资源 的本地化字符串。
        /// </summary>
        public static string InitializeWindow_Title_Download {
            get {
                return ResourceManager.GetString("InitializeWindow_Title_Download", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 当前已是最新版本 的本地化字符串。
        /// </summary>
        public static string LatestVersion {
            get {
                return ResourceManager.GetString("LatestVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 添加文件夹 的本地化字符串。
        /// </summary>
        public static string Launch_AddMinecraftFolder {
            get {
                return ResourceManager.GetString("Launch_AddMinecraftFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 已存在此文件夹 的本地化字符串。
        /// </summary>
        public static string Launch_AddMinecraftFolder_Click_ExistsMinecraftFolder {
            get {
                return ResourceManager.GetString("Launch_AddMinecraftFolder_Click_ExistsMinecraftFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 需选择 .minecraft 文件夹 的本地化字符串。
        /// </summary>
        public static string Launch_AddMinecraftFolder_Click_NeedMinecraftFolder {
            get {
                return ResourceManager.GetString("Launch_AddMinecraftFolder_Click_NeedMinecraftFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 版本隔离 的本地化字符串。
        /// </summary>
        public static string Launch_AloneCore {
            get {
                return ResourceManager.GetString("Launch_AloneCore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 自动扫描 的本地化字符串。
        /// </summary>
        public static string Launch_AutoFindJava {
            get {
                return ResourceManager.GetString("Launch_AutoFindJava", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 扫描完成：发现{|}个Java，其中已有{|}个存在列表中 的本地化字符串。
        /// </summary>
        public static string Launch_AutoFindJava_Click_ScanCompleted {
            get {
                return ResourceManager.GetString("Launch_AutoFindJava_Click_ScanCompleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 让YMCL选择合适的Java 的本地化字符串。
        /// </summary>
        public static string Launch_AutoSelectJava {
            get {
                return ResourceManager.GetString("Launch_AutoSelectJava", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 自定义 的本地化字符串。
        /// </summary>
        public static string Launch_CustomSize {
            get {
                return ResourceManager.GetString("Launch_CustomSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 默认大小 的本地化字符串。
        /// </summary>
        public static string Launch_DefaultSize {
            get {
                return ResourceManager.GetString("Launch_DefaultSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 移除选中项 的本地化字符串。
        /// </summary>
        public static string Launch_DelMinecraftFolder {
            get {
                return ResourceManager.GetString("Launch_DelMinecraftFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 全屏 的本地化字符串。
        /// </summary>
        public static string Launch_FullScreen {
            get {
                return ResourceManager.GetString("Launch_FullScreen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 游戏窗口 的本地化字符串。
        /// </summary>
        public static string Launch_GameWindow {
            get {
                return ResourceManager.GetString("Launch_GameWindow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 导入整合包 的本地化字符串。
        /// </summary>
        public static string Launch_ImportPack {
            get {
                return ResourceManager.GetString("Launch_ImportPack", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 自定义页面 (Xaml) 源代码错误 的本地化字符串。
        /// </summary>
        public static string Launch_Launch_CustomPageSourceError {
            get {
                return ResourceManager.GetString("Launch_Launch_CustomPageSourceError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 启动游戏 的本地化字符串。
        /// </summary>
        public static string Launch_LaunchBtn {
            get {
                return ResourceManager.GetString("Launch_LaunchBtn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 账户错误 的本地化字符串。
        /// </summary>
        public static string Launch_LaunchBtn_Click_AccountError {
            get {
                return ResourceManager.GetString("Launch_LaunchBtn_Click_AccountError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 无法找到正确Java： 的本地化字符串。
        /// </summary>
        public static string Launch_LaunchBtn_Click_CannotFandRightJava {
            get {
                return ResourceManager.GetString("Launch_LaunchBtn_Click_CannotFandRightJava", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 启动完成，等待游戏窗口出现 的本地化字符串。
        /// </summary>
        public static string Launch_LaunchBtn_Click_FinishLaunch {
            get {
                return ResourceManager.GetString("Launch_LaunchBtn_Click_FinishLaunch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 游戏已退出 的本地化字符串。
        /// </summary>
        public static string Launch_LaunchBtn_Click_GameExit {
            get {
                return ResourceManager.GetString("Launch_LaunchBtn_Click_GameExit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Java错误 的本地化字符串。
        /// </summary>
        public static string Launch_LaunchBtn_Click_JavaError {
            get {
                return ResourceManager.GetString("Launch_LaunchBtn_Click_JavaError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 已启动 的本地化字符串。
        /// </summary>
        public static string Launch_LaunchBtn_Click_Launched {
            get {
                return ResourceManager.GetString("Launch_LaunchBtn_Click_Launched", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 启动成功 的本地化字符串。
        /// </summary>
        public static string Launch_LaunchBtn_Click_LaunchSuccess {
            get {
                return ResourceManager.GetString("Launch_LaunchBtn_Click_LaunchSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 未选择游戏核心或未找到游戏 的本地化字符串。
        /// </summary>
        public static string Launch_LaunchBtn_Click_NoChooseGame {
            get {
                return ResourceManager.GetString("Launch_LaunchBtn_Click_NoChooseGame", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 启动游戏 的本地化字符串。
        /// </summary>
        public static string Launch_LaunchGame {
            get {
                return ResourceManager.GetString("Launch_LaunchGame", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 账户错误 的本地化字符串。
        /// </summary>
        public static string Launch_LaunchGame_Click_AccountError {
            get {
                return ResourceManager.GetString("Launch_LaunchGame_Click_AccountError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 YMCL无法找到当前需要的Java：Java 的本地化字符串。
        /// </summary>
        public static string Launch_LaunchGame_Click_CannotFandRightJava {
            get {
                return ResourceManager.GetString("Launch_LaunchGame_Click_CannotFandRightJava", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 启动完成，等待游戏窗口出现 的本地化字符串。
        /// </summary>
        public static string Launch_LaunchGame_Click_FinishLaunch {
            get {
                return ResourceManager.GetString("Launch_LaunchGame_Click_FinishLaunch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 游戏已退出 的本地化字符串。
        /// </summary>
        public static string Launch_LaunchGame_Click_GameExit {
            get {
                return ResourceManager.GetString("Launch_LaunchGame_Click_GameExit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Java错误 的本地化字符串。
        /// </summary>
        public static string Launch_LaunchGame_Click_JavaError {
            get {
                return ResourceManager.GetString("Launch_LaunchGame_Click_JavaError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 启动完成 的本地化字符串。
        /// </summary>
        public static string Launch_LaunchGame_Click_Launched {
            get {
                return ResourceManager.GetString("Launch_LaunchGame_Click_Launched", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 启动成功 的本地化字符串。
        /// </summary>
        public static string Launch_LaunchGame_Click_LaunchSuccess {
            get {
                return ResourceManager.GetString("Launch_LaunchGame_Click_LaunchSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 未选择游戏版本或未找到此版本 的本地化字符串。
        /// </summary>
        public static string Launch_LaunchGame_Click_NoChooseGame {
            get {
                return ResourceManager.GetString("Launch_LaunchGame_Click_NoChooseGame", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 获取版本列表发生错误 的本地化字符串。
        /// </summary>
        public static string Launch_LoadMinecraftVersion_GetVersionListError {
            get {
                return ResourceManager.GetString("Launch_LoadMinecraftVersion_GetVersionListError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 手动添加 的本地化字符串。
        /// </summary>
        public static string Launch_ManualAddJava {
            get {
                return ResourceManager.GetString("Launch_ManualAddJava", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 已存在此Java 的本地化字符串。
        /// </summary>
        public static string Launch_ManualAddJava_Click_ExistsJava {
            get {
                return ResourceManager.GetString("Launch_ManualAddJava_Click_ExistsJava", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 最大运行内存 的本地化字符串。
        /// </summary>
        public static string Launch_MaxMem {
            get {
                return ResourceManager.GetString("Launch_MaxMem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Minecraft文件夹 的本地化字符串。
        /// </summary>
        public static string Launch_MinecraftFolder {
            get {
                return ResourceManager.GetString("Launch_MinecraftFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 &lt;未选择游戏核心&gt; 的本地化字符串。
        /// </summary>
        public static string Launch_NoChooseGame {
            get {
                return ResourceManager.GetString("Launch_NoChooseGame", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 显示输出日志 的本地化字符串。
        /// </summary>
        public static string Launch_OutputLogReceived {
            get {
                return ResourceManager.GetString("Launch_OutputLogReceived", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 刷新 的本地化字符串。
        /// </summary>
        public static string Launch_Refresh {
            get {
                return ResourceManager.GetString("Launch_Refresh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Mods 的本地化字符串。
        /// </summary>
        public static string Launch_TabItem_Mods {
            get {
                return ResourceManager.GetString("Launch_TabItem_Mods", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 概览 的本地化字符串。
        /// </summary>
        public static string Launch_TabItem_Overview {
            get {
                return ResourceManager.GetString("Launch_TabItem_Overview", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 设置 的本地化字符串。
        /// </summary>
        public static string Launch_TabItem_Settings {
            get {
                return ResourceManager.GetString("Launch_TabItem_Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似  版本列表  的本地化字符串。
        /// </summary>
        public static string Launch_ToVersionList {
            get {
                return ResourceManager.GetString("Launch_ToVersionList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似  版本设置  的本地化字符串。
        /// </summary>
        public static string Launch_ToVersionSetting {
            get {
                return ResourceManager.GetString("Launch_ToVersionSetting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 版本列表 的本地化字符串。
        /// </summary>
        public static string Launch_VersionList {
            get {
                return ResourceManager.GetString("Launch_VersionList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 自定义主界面 的本地化字符串。
        /// </summary>
        public static string Launcher_SettingItem_CustomMainPage {
            get {
                return ResourceManager.GetString("Launcher_SettingItem_CustomMainPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 编辑 的本地化字符串。
        /// </summary>
        public static string Launcher_SettingItem_EditCustomHomePage {
            get {
                return ResourceManager.GetString("Launcher_SettingItem_EditCustomHomePage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 语言 的本地化字符串。
        /// </summary>
        public static string Launcher_SettingItem_Language {
            get {
                return ResourceManager.GetString("Launcher_SettingItem_Language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 将启用自定义页面，YMCL不保证自定义内容安全性，不安全的自定义内容可能会导致设备遭受攻击等 的本地化字符串。
        /// </summary>
        public static string Launcher_UseCustomHomePageToggle_Toggled_On_Info {
            get {
                return ResourceManager.GetString("Launcher_UseCustomHomePageToggle_Toggled_On_Info", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 启动失败 的本地化字符串。
        /// </summary>
        public static string LaunchFail {
            get {
                return ResourceManager.GetString("LaunchFail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 浅色 的本地化字符串。
        /// </summary>
        public static string Light {
            get {
                return ResourceManager.GetString("Light", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似    下载 的本地化字符串。
        /// </summary>
        public static string MainWindow_NavigationDownload {
            get {
                return ResourceManager.GetString("MainWindow_NavigationDownload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似    启动 的本地化字符串。
        /// </summary>
        public static string MainWindow_NavigationLaunch {
            get {
                return ResourceManager.GetString("MainWindow_NavigationLaunch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似    更多 的本地化字符串。
        /// </summary>
        public static string MainWindow_NavigationMore {
            get {
                return ResourceManager.GetString("MainWindow_NavigationMore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似    设置 的本地化字符串。
        /// </summary>
        public static string MainWindow_NavigationSetting {
            get {
                return ResourceManager.GetString("MainWindow_NavigationSetting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 YMCL 的本地化字符串。
        /// </summary>
        public static string MainWindow_Title {
            get {
                return ResourceManager.GetString("MainWindow_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 最大下载线程 的本地化字符串。
        /// </summary>
        public static string MaximumDownloadThread {
            get {
                return ResourceManager.GetString("MaximumDownloadThread", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 开源项目使用表 的本地化字符串。
        /// </summary>
        public static string OpenSourceProjectUsageTable {
            get {
                return ResourceManager.GetString("OpenSourceProjectUsageTable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 已取消保存 的本地化字符串。
        /// </summary>
        public static string SaveCancel {
            get {
                return ResourceManager.GetString("SaveCancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 保存皮肤文件 的本地化字符串。
        /// </summary>
        public static string SaveSkin {
            get {
                return ResourceManager.GetString("SaveSkin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 保存成功 的本地化字符串。
        /// </summary>
        public static string SaveSuccess {
            get {
                return ResourceManager.GetString("SaveSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 启动器 的本地化字符串。
        /// </summary>
        public static string Setting_Navigation_About {
            get {
                return ResourceManager.GetString("Setting_Navigation_About", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 账户 的本地化字符串。
        /// </summary>
        public static string Setting_Navigation_Account {
            get {
                return ResourceManager.GetString("Setting_Navigation_Account", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 下载 的本地化字符串。
        /// </summary>
        public static string Setting_Navigation_Download {
            get {
                return ResourceManager.GetString("Setting_Navigation_Download", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 启动 的本地化字符串。
        /// </summary>
        public static string Setting_Navigation_Launch {
            get {
                return ResourceManager.GetString("Setting_Navigation_Launch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 个性化 的本地化字符串。
        /// </summary>
        public static string Setting_Navigation_Launcher {
            get {
                return ResourceManager.GetString("Setting_Navigation_Launcher", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 任务进度 的本地化字符串。
        /// </summary>
        public static string TaskProgressWindow_Title {
            get {
                return ResourceManager.GetString("TaskProgressWindow_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 更新内容 的本地化字符串。
        /// </summary>
        public static string UpdateInfo {
            get {
                return ResourceManager.GetString("UpdateInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 正在验证账户 的本地化字符串。
        /// </summary>
        public static string VerifyingAccount {
            get {
                return ResourceManager.GetString("VerifyingAccount", resourceCulture);
            }
        }
    }
}
