//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace YMCL.Main.UI.Lang {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class MainLang {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal MainLang() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("YMCL.Main.UI.Lang.MainLang", typeof(MainLang).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   重写当前线程的 CurrentUICulture 属性，对
        ///   使用此强类型资源类的所有资源查找执行重写。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 YMCL发生未处理的异常 的本地化字符串。
        /// </summary>
        public static string App_UnhandledException {
            get {
                return ResourceManager.GetString("App_UnhandledException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 连接中 的本地化字符串。
        /// </summary>
        public static string InitializeWindow_Connecting {
            get {
                return ResourceManager.GetString("InitializeWindow_Connecting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 连接失败 的本地化字符串。
        /// </summary>
        public static string InitializeWindow_ConnectionFailed {
            get {
                return ResourceManager.GetString("InitializeWindow_ConnectionFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 连接超时 的本地化字符串。
        /// </summary>
        public static string InitializeWindow_ConnectionTimeout {
            get {
                return ResourceManager.GetString("InitializeWindow_ConnectionTimeout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 需要管理员权限以初始化YMCL，点击确定使用管理员权限重启程序 的本地化字符串。
        /// </summary>
        public static string InitializeWindow_Download_AdministratorPermissionRequired {
            get {
                return ResourceManager.GetString("InitializeWindow_Download_AdministratorPermissionRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 下载完成 的本地化字符串。
        /// </summary>
        public static string InitializeWindow_DownloadFinish {
            get {
                return ResourceManager.GetString("InitializeWindow_DownloadFinish", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 等待中 的本地化字符串。
        /// </summary>
        public static string InitializeWindow_DownloadWaiting {
            get {
                return ResourceManager.GetString("InitializeWindow_DownloadWaiting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 获取管理员权限失败，YMCL初始化失败 的本地化字符串。
        /// </summary>
        public static string InitializeWindow_FailedToObtainAdministratorPrivileges {
            get {
                return ResourceManager.GetString("InitializeWindow_FailedToObtainAdministratorPrivileges", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 YMCL初始化完成 的本地化字符串。
        /// </summary>
        public static string InitializeWindow_InitializeFinish {
            get {
                return ResourceManager.GetString("InitializeWindow_InitializeFinish", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 下一步 → 的本地化字符串。
        /// </summary>
        public static string InitializeWindow_NextSetpBtn {
            get {
                return ResourceManager.GetString("InitializeWindow_NextSetpBtn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 YMCL初始化 的本地化字符串。
        /// </summary>
        public static string InitializeWindow_Title {
            get {
                return ResourceManager.GetString("InitializeWindow_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 YMCL - 下载资源 的本地化字符串。
        /// </summary>
        public static string InitializeWindow_Title_Download {
            get {
                return ResourceManager.GetString("InitializeWindow_Title_Download", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 自定义主界面 的本地化字符串。
        /// </summary>
        public static string Launcher_SettingItem_CustomMainPage {
            get {
                return ResourceManager.GetString("Launcher_SettingItem_CustomMainPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 编辑 的本地化字符串。
        /// </summary>
        public static string Launcher_SettingItem_EditCustomHomePage {
            get {
                return ResourceManager.GetString("Launcher_SettingItem_EditCustomHomePage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 语言 的本地化字符串。
        /// </summary>
        public static string Launcher_SettingItem_Language {
            get {
                return ResourceManager.GetString("Launcher_SettingItem_Language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似    下载 的本地化字符串。
        /// </summary>
        public static string MainWindow_NavigationDownload {
            get {
                return ResourceManager.GetString("MainWindow_NavigationDownload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似    启动 的本地化字符串。
        /// </summary>
        public static string MainWindow_NavigationLaunch {
            get {
                return ResourceManager.GetString("MainWindow_NavigationLaunch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似    更多 的本地化字符串。
        /// </summary>
        public static string MainWindow_NavigationMore {
            get {
                return ResourceManager.GetString("MainWindow_NavigationMore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似    设置 的本地化字符串。
        /// </summary>
        public static string MainWindow_NavigationSetting {
            get {
                return ResourceManager.GetString("MainWindow_NavigationSetting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 YMCL 的本地化字符串。
        /// </summary>
        public static string MainWindow_Title {
            get {
                return ResourceManager.GetString("MainWindow_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 关于 的本地化字符串。
        /// </summary>
        public static string Setting_Navigation_About {
            get {
                return ResourceManager.GetString("Setting_Navigation_About", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 账户 的本地化字符串。
        /// </summary>
        public static string Setting_Navigation_Account {
            get {
                return ResourceManager.GetString("Setting_Navigation_Account", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 下载 的本地化字符串。
        /// </summary>
        public static string Setting_Navigation_Download {
            get {
                return ResourceManager.GetString("Setting_Navigation_Download", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 启动 的本地化字符串。
        /// </summary>
        public static string Setting_Navigation_Launch {
            get {
                return ResourceManager.GetString("Setting_Navigation_Launch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 启动器 的本地化字符串。
        /// </summary>
        public static string Setting_Navigation_Launcher {
            get {
                return ResourceManager.GetString("Setting_Navigation_Launcher", resourceCulture);
            }
        }
    }
}
